name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cloudflare-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy app/dist --project-name=deminearchiver
